name: Android Build for SmartPI ONE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape pour nettoyer l'espace disque
      - name: Clean up disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          df -h  # Vérifier l'espace disque disponible

      # Vérifier le code source
      - uses: actions/checkout@v4

      # Installer JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Installer les dépendances requises
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk git-core gnupg flex bison gperf build-essential \
          zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
          lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev \
          libgl1-mesa-dev libxml2-utils xsltproc unzip bc python3

          # Installer repo
          mkdir -p ~/bin
          curl -o ~/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> $GITHUB_ENV

      # Synchroniser la source AOSP
      - name: Sync AOSP source
        run: |
          mkdir -p ~/android-source
          cd ~/android-source
          export PATH=~/bin:$PATH
          repo init -u https://android.googlesource.com/platform/manifest -b android-11.0.0_r1
          repo sync -j2  # Utiliser moins de threads pour éviter de saturer l'espace

      # Copier les fichiers spécifiques au NanoPi M1
      - name: Copy NanoPi M1-specific files
        run: |
          cp -r $GITHUB_WORKSPACE/device/friendlyarm/smartpi_one/* ~/android-source/device/friendlyarm/smartpi_one/

      # Compiler Android pour NanoPi M1
      - name: Build Android for NanoPi M1
        run: |
          cd ~/android-source
          source build/envsetup.sh
          lunch aosp_smartpi_one-userdebug
          make -j4  # Utiliser moins de threads

      # Télécharger l'image compilée
      - name: Upload built image
        uses: actions/upload-artifact@v3
        with:
          name: android-image
          path: out/target/product/smartpi_one/
