name: Android Build for SmartPI ONE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Checkout le code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2: Configurer JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Étape 3: Installer les dépendances nécessaires à la compilation Android
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk git-core gnupg flex bison gperf build-essential \
          zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
          lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev \
          libgl1-mesa-dev libxml2-utils xsltproc unzip bc python3

          # Installer repo
          mkdir -p ~/bin
          curl -o ~/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
          chmod a+x ~/bin/repo
          
          # Ajouter ~/bin au PATH pour la session actuelle
          echo 'export PATH=~/bin:$PATH' >> $GITHUB_ENV

      # Étape 4: Synchroniser les sources AOSP (si elles ne sont pas mises en cache)
      - name: Sync AOSP source (if not cached)
        run: |
          mkdir -p ~/android-source
          cd ~/android-source
          repo init -u https://android.googlesource.com/platform/manifest -b android-11.0.0_r1
          repo sync -j4

      # Étape 5: Copier les fichiers spécifiques à NanoPi M1
      - name: Copy NanoPi M1-specific files
        run: |
          cp -r $GITHUB_WORKSPACE/device/friendlyarm/smartpi_one/* ~/android-source/device/friendlyarm/smartpi_one/

      # Étape 6: Compiler Android pour NanoPi M1
      - name: Build Android for NanoPi M1
        run: |
          cd ~/android-source
          source build/envsetup.sh
          lunch aosp_smartpi_one-userdebug
          make -j8

      # Étape 7: Téléverser l'image compilée
      - name: Upload built image
        uses: actions/upload-artifact@v3
        with:
          name: android-image
          path: out/target/product/smartpi_one/
