name: Android Build for SmartPI ONE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./app  # Changez 'app' par le répertoire où se trouvent les fichiers Gradle si nécessaire

      - name: Upload built image
        uses: actions/upload-artifact@v3
        with:
          name: android-image
          path: ./app/build/outputs/  # Spécifiez le bon chemin de sortie
