name: Android Build for SmartPI ONE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Mise à jour vers la version compatible Node.js 20

      - name: Set up JDK
        uses: actions/setup-java@v3  # Mise à jour vers la version compatible Node.js 20
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk git-core gnupg flex bison gperf build-essential \
          zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
          lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev \
          libgl1-mesa-dev libxml2-utils xsltproc unzip bc python3

          # Installer repo
          mkdir -p ~/bin
          curl -o ~/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
          chmod a+x ~/bin/repo

          # Ajouter ~/bin au PATH pour la session actuelle
          echo 'export PATH=~/bin:$PATH' >> $GITHUB_ENV

      - name: Cache AOSP source
        uses: actions/cache@v3  # Mise à jour vers la version compatible Node.js 20
        with:
          path: ~/android-source
          key: ${{ runner.os }}-aosp-${{ hashFiles('**/Android.bp') }}
          restore-keys: |
            ${{ runner.os }}-aosp

      - name: Sync AOSP source (if not cached)
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/android-source
          cd ~/android-source
          # Réaffecter le PATH ici pour s'assurer que repo est accessible
          export PATH=~/bin:$PATH
          repo init -u https://android.googlesource.com
